### ISSUE TITLE
KeyError: "CascadeRCNN: 'RepLKNet is not in the models registry

### ISSUE THREAD

**Issue by Williamlizl** [DingXiaoH/RepLKNet-pytorch#18]
`2022-04-08 13:36:40,827 - mmdet - INFO - Set random seed to 687365578, deterministic: False
Traceback (most recent call last):
  File "/home/lbc/.local/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/lbc/.local/lib/python3.7/site-packages/mmdet/models/detectors/cascade_rcnn.py", line 28, in __init__
    init_cfg=init_cfg)
  File "/home/lbc/.local/lib/python3.7/site-packages/mmdet/models/detectors/two_stage.py", line 32, in __init__
    self.backbone = build_backbone(backbone)
  File "/home/lbc/.local/lib/python3.7/site-packages/mmdet/models/builder.py", line 20, in build_backbone
    return BACKBONES.build(cfg)
  File "/home/lbc/.local/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/lbc/.local/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/lbc/.local/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')`

**Comment by DingXiaoH** [comment]
mmdetection/mmdet/models/backbones/__init__.py.
